In [61]:

import os
print(os.getcwd())
print(os.listdir())

C:\Users\Shreshtha Pandey\crop recommendation system
['.git', '.gitignore', '.ipynb_checkpoints', 'app.py', 'APY.csv', 'APY_original.csv', 'APY_recovered.csv', 'archive', 'archive (17).zip', 'crop recommendation notebook.ipynb', 'crop yield notebook.ipynb', 'crop_clean.csv', 'crop_data', 'crop_reference.csv', 'crop_weather.csv', 'data', 'districts_list.csv', 'district_latlon.csv', 'district_latlon_final.csv', 'district_latlon_partial.csv', 'final_data.csv', 'final_model.pkl', 'get_latlon.py', 'get_weather.py', 'get_weather_top.py', 'get_weather_yearly.py', 'Market_Wise_Price_Arrival_17-10-2026_11-03-04_PM.csv', 'pyproject.toml', 'requirements.txt', 'run_weather.py', 'state_weather.csv', 'top_districts.csv', 'weather_partial_old.csv', 'weather_top_partial.csv', 'weather_yearly_partial.csv', '__pycache__']

In [62]:
import zipfile
import os

zip_path = r"C:\Users\Shreshtha Pandey\Downloads\archive (17).zip"
extract_path = r"C:\Users\Shreshtha Pandey\Downloads\extracted_files"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("ZIP file extracted successfully!")

ZIP file extracted successfully!

In [63]:
print(os.listdir(extract_path))

['crop_yield.csv', 'Indian_crop_production_yield_dataset.csv']

In [64]:
import pandas as pd

df1 = pd.read_csv(
    r"C:\Users\Shreshtha Pandey\Downloads\extracted_files\Indian_crop_production_yield_dataset.csv"
)

df2 = pd.read_csv(
    r"C:\Users\Shreshtha Pandey\Downloads\extracted_files\crop_yield.csv"
)

display(df1.head())
display(df2.head())

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,yield
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0,1.594896
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0,0.500000
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0,3.147059
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0,3.642045
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0,0.229167

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.420909

In [65]:
print(df1.shape, df2.shape)
df1 = df1.rename(columns={"State_Name": "State",
                          "District_Name": "District",
                          "yield": "Yield"})
print(df1.columns.tolist())

(575879, 8) (19689, 10)
['State', 'District', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production', 'Yield']

In [66]:
for d in (df1, df2):
    d["Crop"] = d["Crop"].str.strip().str.lower()
    d["State"] = d["State"].str.strip().str.lower()
    d["Season"] = d["Season"].str.strip().str.lower()

df1["District"] = df1["District"].str.strip().str.lower()

In [67]:
print("df1 me hai, df2 me nahi:", set(df1.State) - set(df2.State))
print("df2 me hai, df1 me nahi:", set(df2.State) - set(df1.State))

df1 me hai, df2 me nahi: {'dadra and nagar haveli', 'chandigarh', 'andaman and nicobar islands', 'daman and diu', 'rajasthan', 'laddakh'}
df2 me hai, df1 me nahi: set()

In [68]:
df1["State"] = df1["State"].replace({"laddakh": "ladakh"})
print(sorted(df1["State"].unique()))
print(sorted(df2.State.unique()))

['andaman and nicobar islands', 'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chandigarh', 'chhattisgarh', 'dadra and nagar haveli', 'daman and diu', 'delhi', 'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jammu and kashmir', 'jharkhand', 'karnataka', 'kerala', 'ladakh', 'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'rajasthan', 'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal']
['andhra pradesh', 'arunachal pradesh', 'assam', 'bihar', 'chhattisgarh', 'delhi', 'goa', 'gujarat', 'haryana', 'himachal pradesh', 'jammu and kashmir', 'jharkhand', 'karnataka', 'kerala', 'madhya pradesh', 'maharashtra', 'manipur', 'meghalaya', 'mizoram', 'nagaland', 'odisha', 'puducherry', 'punjab', 'sikkim', 'tamil nadu', 'telangana', 'tripura', 'uttar pradesh', 'uttarakhand', 'west bengal']

In [69]:
df2["Fert_per_ha"] = df2["Fertilizer"] / df2["Area"]
df2["Pest_per_ha"] = df2["Pesticide"] / df2["Area"]

print(df2[["Fert_per_ha", "Pest_per_ha"]].describe())

        Fert_per_ha   Pest_per_ha
count  19689.000000  19689.000000
mean     137.160208      0.274374
std       26.200647      0.073284
min       94.670000      0.090000
25%      108.340000      0.220000
50%      144.490000      0.270000
75%      157.910000      0.330000
max      193.610000      0.380000

In [70]:
ref = (df2.groupby(["State", "Crop"])
          .agg(Rain_avg=("Annual_Rainfall", "mean"),
               Fert_per_ha=("Fert_per_ha", "mean"),
               Pest_per_ha=("Pest_per_ha", "mean"))
          .reset_index())

print(ref.shape)
ref.head()
# Kya ho raha hai: Har (state, crop) jodi ke liye average rainfall, fertilizer/ha aur pesticide/ha nikal rahe hain. Isse ref variable ban jayega.

(995, 5)

            State          Crop    Rain_avg  Fert_per_ha  Pest_per_ha
0  andhra pradesh      arecanut  922.805556   140.160000     0.275556
1  andhra pradesh     arhar/tur  919.419512   134.464878     0.272683
2  andhra pradesh         bajra  913.731111   134.094889     0.268667
3  andhra pradesh        banana  912.422222   137.801111     0.270000
4  andhra pradesh  black pepper  980.750000   158.125000     0.320000

In [71]:
proxy = {
    "rajasthan": "haryana",
    "chandigarh": "punjab",
    "dadra and nagar haveli": "gujarat",
    "daman and diu": "gujarat",
    "ladakh": "himachal pradesh",
    "andaman and nicobar islands": "kerala",
}

available = set(ref.State)
for k, v in proxy.items():
    print(k, "->", v, "| df2 me hai:", v in available)

rajasthan -> haryana | df2 me hai: True
chandigarh -> punjab | df2 me hai: True
dadra and nagar haveli -> gujarat | df2 me hai: True
daman and diu -> gujarat | df2 me hai: True
ladakh -> himachal pradesh | df2 me hai: True
andaman and nicobar islands -> kerala | df2 me hai: True

In [72]:
extra = []
for new_state, old_state in proxy.items():
    tmp = ref[ref.State == old_state].copy()
    tmp["State"] = new_state
    extra.append(tmp)

ref_full = pd.concat([ref] + extra, ignore_index=True)
print(ref.shape, "->", ref_full.shape)
print(sorted(set(df1.State) - set(ref_full.State)))

(995, 5) -> (1190, 5)
[]

In [73]:
import pandas as pd
import numpy as np

for v in ["df", "ref", "ref_full", "extra", "cmp", "rice"]:
    globals().pop(v, None)

df1 = pd.read_csv(r"C:\Users\Shreshtha Pandey\Downloads\extracted_files\Indian_crop_production_yield_dataset.csv")
df2 = pd.read_csv(r"C:\Users\Shreshtha Pandey\Downloads\extracted_files\crop_yield.csv")
print(df1.shape, df2.shape)

(575879, 8) (19689, 10)

In [74]:
df2["Production"] = df2["Production"] * 10   # ton -> quintal
df2["Yield"] = df2["Yield"] * 10             # t/ha -> q/ha
print(df2[["Crop", "Area", "Production", "Yield"]].head())

           Crop     Area  Production         Yield
0      Arecanut  73814.0      567080      7.960870
1     Arhar/Tur   6637.0       46850      7.104348
2   Castor seed    796.0         220      2.383333
3      Coconut   19656.0  1269050000  52380.517390
4  Cotton(lint)   1739.0        7940      4.209091

In [75]:
chk2 = df2["Production"] / df2["Area"]
print("df2 mismatch:", (abs(chk2 - df2["Yield"]) > 0.01).sum())

chk1 = df1["Production"] / df1["Area"]
print("df1 mismatch:", (abs(chk1 - df1["yield"]) > 0.01).sum())

df2 mismatch: 18570
df1 mismatch: 0

In [76]:
for d in (df1, df2):
    d["Crop"] = d["Crop"].str.strip().str.lower()

a = df1[df1.Area > 0].assign(Y=lambda x: x.Production / x.Area).groupby("Crop")["Y"].median().rename("df1_q_ha")
b = df2.groupby("Crop")["Yield"].median().rename("df2_q_ha")
cmp = pd.concat([a, b], axis=1).dropna()
cmp["ratio"] = cmp["df1_q_ha"] / cmp["df2_q_ha"]
print(cmp.ratio.describe())
print(cmp.loc[["rice", "wheat", "maize", "sugarcane"]].round(2))

count    55.000000
mean      5.344331
std       1.372276
min       0.072651
25%       4.497868
50%       5.432422
75%       6.227780
max       9.633197
Name: ratio, dtype: float64
           df1_q_ha  df2_q_ha  ratio
Crop
rice         108.95     22.04   4.94
wheat        112.47     16.68   6.74
maize        112.50     19.55   5.75
sugarcane   2545.45    531.58   4.79

In [78]:

x = df1[(df1["State_Name"].str.strip().str.lower() == "punjab") & (df1["Crop"] == "rice")]
g = x.groupby("Crop_Year")[["Area", "Production"]].sum()
g["weighted_yield_q_ha"] = g["Production"] / g["Area"]
print(g.tail(8).round(1))
print("Rows:", len(x), "| row-wise median yield:", round(x["yield"].median(), 1))

                Area    Production  weighted_yield_q_ha
Crop_Year
2012       5698000.0  1.150390e+09                201.9
2013       5702000.0  1.137967e+09                199.6
2014       5788000.0  1.121807e+09                193.8
2015       2975000.0  1.182300e+09                397.4
2016       3046000.0  1.263800e+09                414.9
2017       3065000.0  1.338200e+09                436.6
2018       3103000.0  1.282200e+09                413.2
2019       3142000.0  1.267500e+09                403.4
Rows: 786 | row-wise median yield: 305.5

In [79]:
d = df1[df1["Crop"] == "rice"].groupby("Crop_Year")[["Area", "Production"]].sum()
d["q_ha_after_div10"] = d["Production"] / 10 / d["Area"]
print(d.round(1).tail(12))

                 Area    Production  q_ha_after_div10
Crop_Year
2009       79306238.0  8.969761e+09              11.3
2010       81019911.0  9.714803e+09              12.0
2011       82564645.5  1.059949e+10              12.8
2012       94118843.0  1.085483e+10              11.5
2013       81371905.2  1.123069e+10              13.8
2014       79658734.1  1.156764e+10              14.5
2015       47149403.0  1.018563e+10              21.6
2016       44128759.5  1.189361e+10              27.0
2017       44591061.8  1.181793e+10              26.5
2018       45337851.3  1.186900e+10              26.2
2019       47354250.1  1.346315e+10              28.4
2020         257251.0  7.244290e+07              28.2

In [80]:
x = df1[(df1["Crop"] == "rice") & (df1["District_Name"].str.lower() == "ludhiana")]
print(x[["Crop_Year", "Season", "Area", "Production"]].sort_values("Crop_Year").tail(30).to_string())

        Crop_Year  Season      Area   Production
160194       2002  Kharif  236000.0    1020000.0
160204       2003  Kharif  241000.0    1047000.0
265068       2003  Kharif  241000.0  104700000.0
306846       2004  Kharif  400000.0  114400000.0
160215       2004  Kharif  400000.0    1144000.0
160227       2005  Kharif  250000.0    1130000.0
306847       2005  Kharif  250000.0  113000000.0
306848       2006  Kharif  248000.0  108400000.0
160238       2006  Kharif  248000.0    1084000.0
349634       2007  Kharif  250000.0  113300000.0
160247       2007  Kharif  250000.0    1133000.0
160255       2008  Kharif  254000.0    1135000.0
349635       2008  Kharif  254000.0  113500000.0
349636       2009  Kharif  257000.0  120600000.0
160264       2009  Kharif  257000.0    1206000.0
160274       2010  Kharif  257000.0    1133000.0
395615       2010  Kharif  257000.0  113300000.0
395616       2011  Kharif  257000.0  109400000.0
160283       2011  Kharif  257000.0    1094000.0
160294       2012  Kharif  257000.0    1169000.0
395617       2012  Kharif  257000.0  116900000.0
160307       2013  Kharif  257000.0    1137000.0
440064       2013  Kharif  257000.0  113700000.0
440065       2014  Kharif  257000.0  111900000.0
160316       2014  Kharif  257000.0    1119000.0
440066       2015  Kharif  257000.0  118100000.0
490759       2016  Kharif  259000.0  124700000.0
490760       2017  Kharif  258000.0  122400000.0
490761       2018  Kharif  259000.0  115300000.0
522262       2019  Kharif  259000.0  121100000.0

In [81]:
d = df1[df1.Crop_Year < 2020].copy()
key = ["State_Name", "District_Name", "Crop_Year", "Season", "Crop", "Area"]
d = d.sort_values("Production", ascending=False).drop_duplicates(key, keep="first")
print(df1.shape, "->", d.shape)

(575879, 8) -> (363187, 8)

In [82]:
d["Yield_q_ha"] = d["Production"] / 10 / d["Area"]
d = d[(d.Area > 0) & (d.Yield_q_ha > 0)]
for c in ["rice", "wheat", "maize", "sugarcane"]:
    print(c, round(d[d.Crop == c]["Yield_q_ha"].median(), 1))

rice 20.1
wheat 20.0
maize 19.0
sugarcane 542.4

In [83]:
w = d[d.Crop.isin(["rice", "wheat", "maize", "sugarcane"])].groupby(["Crop", "Crop_Year"])[["Area", "Production"]].sum()
w["q_ha"] = w["Production"] / 10 / w["Area"]
print(w["q_ha"].unstack(0).loc[2013:2019].round(1))

Crop       maize  rice  sugarcane  wheat
Crop_Year
2013        30.2  24.9      710.2   32.5
2014        27.5  24.4      713.3   27.2
2015        26.3  23.6      694.4   31.1
2016        29.4  27.0      726.1   35.7
2017        35.3  26.5      794.9   36.5
2018        31.3  26.2      783.0   37.4
2019        32.9  28.4      798.8   37.0

In [86]:
d["Yield_q_ha"].groupby(d.Crop).quantile(0.99).sort_values(ascending=False).head(10).round(0)
# Kya ho raha hai: Har crop ka 99th percentile nikal rahe hain, taaki pata chale kahin kuch rows ab bhi impossible hain (jaise Area bahut chhota aur Production bahut bada).

Crop
coconut           215155.0
sugarcane           1307.0
banana               857.0
tapioca              507.0
onion                343.0
potato               333.0
ginger               319.0
sweet potato         267.0
turmeric             235.0
other oilseeds       224.0
Name: Yield_q_ha, dtype: float64

In [87]:
cols = ["State_Name", "District_Name", "Crop_Year", "Crop", "Area", "Production", "Yield_q_ha"]
print(d.sort_values("Yield_q_ha", ascending=False)[cols].head(10).to_string())

            State_Name  District_Name  Crop_Year     Crop     Area    Production     Yield_q_ha
460330           Assam       TINSUKIA       2018  coconut     72.0  3.165000e+08  439583.333333
318055     West Bengal        BIRBHUM       2006  coconut    509.0  1.974920e+09  388000.000000
353003      Tamil Nadu          ERODE       2008  coconut  10014.0  3.318000e+10  331336.129419
511148           Assam       TINSUKIA       2019  coconut     71.0  2.340000e+08  329577.464789
457172  Andhra Pradesh       PRAKASAM       2018  coconut     19.0  6.000000e+07  315789.473684
412024           Assam       TINSUKIA       2015  coconut     75.0  2.257000e+08  300933.333333
510011  Andhra Pradesh  WEST GODAVARI       2019  coconut  23316.0  6.941640e+10  297720.020587
460328           Assam       TINSUKIA       2016  coconut     76.0  2.188000e+08  287894.736842
280944           Assam         KAMRUP       2005  coconut   2026.0  5.740500e+09  283341.559724
239752           Assam      LAKHIMPUR       2001  coconut    192.0  5.044000e+08  262708.333333

In [88]:
d = d[d.Crop != "coconut"].copy()

cap = d.groupby("Crop")["Yield_q_ha"].transform(lambda x: x.quantile(0.99))
print("Rows capped se upar:", (d["Yield_q_ha"] > cap).sum())

d = d[d["Yield_q_ha"] <= cap]
print(d.shape)

Rows capped se upar: 3564
(352965, 9)

In [89]:
d = d.rename(columns={"State_Name": "State",
                      "District_Name": "District",
                      "yield": "Yield_old"})

for c in ["State", "District", "Season", "Crop"]:
    d[c] = d[c].str.strip().str.lower()

d["State"] = d["State"].replace({"laddakh": "ladakh"})
print(d.columns.tolist())
print(d[["State", "District", "Season", "Crop"]].head())

['State', 'District', 'Crop_Year', 'Season', 'Crop', 'Area', 'Production', 'Yield_old', 'Yield_q_ha']
                State District      Season       Crop
505938  uttar pradesh    kheri      kharif  sugarcane
527594  uttar pradesh    kheri      kharif  sugarcane
477958      karnataka  belgaum  whole year  sugarcane
434884    maharashtra  solapur  whole year  sugarcane
505937  uttar pradesh    kheri      kharif  sugarcane

In [90]:
d = d.drop(columns=["Yield_old", "Production"])
print(d.shape)
d.head()

(352965, 7)

,State,District,Crop_Year,Season,Crop,Area,Yield_q_ha
505938,uttar pradesh,kheri,2018,kharif,sugarcane,239675.0,863.400021
527594,uttar pradesh,kheri,2019,kharif,sugarcane,237847.0,868.479989
477958,karnataka,belgaum,2017,whole year,sugarcane,208729.0,987.999990
434884,maharashtra,solapur,2014,whole year,sugarcane,205500.0,975.654501
505937,uttar pradesh,kheri,2017,kharif,sugarcane,248135.0,807.080017

In [91]:
d.head()

,State,District,Crop_Year,Season,Crop,Area,Yield_q_ha
505938,uttar pradesh,kheri,2018,kharif,sugarcane,239675.0,863.400021
527594,uttar pradesh,kheri,2019,kharif,sugarcane,237847.0,868.479989
477958,karnataka,belgaum,2017,whole year,sugarcane,208729.0,987.999990
434884,maharashtra,solapur,2014,whole year,sugarcane,205500.0,975.654501
505937,uttar pradesh,kheri,2017,kharif,sugarcane,248135.0,807.080017

In [93]:
df1.head()
df2.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield
0,arecanut,1997,Whole Year,Assam,73814.0,567080,2051.4,7024878.38,22882.34,7.960870
1,arhar/tur,1997,Kharif,Assam,6637.0,46850,2051.4,631643.29,2057.47,7.104348
2,castor seed,1997,Kharif,Assam,796.0,220,2051.4,75755.32,246.76,2.383333
3,coconut,1997,Whole Year,Assam,19656.0,1269050000,2051.4,1870661.52,6093.36,52380.517390
4,cotton(lint),1997,Kharif,Assam,1739.0,7940,2051.4,165500.63,539.09,4.209091

In [94]:
print(d["Season"].unique())
print("Districts:", d["District"].nunique())

<ArrowStringArray>
['kharif', 'whole year', 'rabi', 'winter', 'summer', 'autumn']
Length: 6, dtype: str
Districts: 730

In [95]:
season_map = {
    "kharif": "kharif",
    "rabi": "rabi",
    "winter": "rabi",
    "summer": "zaid",
    "autumn": "kharif",
    "whole year": "whole year",
}

d["Season"] = d["Season"].map(season_map)
print("Unmapped (NaN):", d["Season"].isna().sum())
print(d["Season"].value_counts())

Unmapped (NaN): 0
Season
kharif        147991
rabi          113473
whole year     69472
zaid           22029
Name: count, dtype: int64

In [96]:
key = ["State", "District", "Crop_Year", "Season", "Crop", "Area"]
print("Duplicates:", d.duplicated(key).sum())

Duplicates: 18

In [97]:
d = d.drop_duplicates(key, keep="first").copy()
print(d.shape)

(352947, 7)

In [98]:
df2["Crop"] = df2["Crop"].str.strip().str.lower()
df2["State"] = df2["State"].str.strip().str.lower()

df2["Fert_per_ha"] = df2["Fertilizer"] / df2["Area"]
df2["Pest_per_ha"] = df2["Pesticide"] / df2["Area"]

ref = (df2.groupby(["State", "Crop"])
          .agg(Rain_avg=("Annual_Rainfall", "mean"),
               Fert_per_ha=("Fert_per_ha", "mean"),
               Pest_per_ha=("Pest_per_ha", "mean"))
          .reset_index())
print(ref.shape)
print(ref[["Rain_avg", "Fert_per_ha", "Pest_per_ha"]].describe().round(1))

(995, 5)
       Rain_avg  Fert_per_ha  Pest_per_ha
count     995.0        995.0        995.0
mean     1475.4        137.6          0.3
std       796.4         13.4          0.0
min       389.7         94.7          0.1
25%       988.4        133.2          0.3
50%      1202.1        136.3          0.3
75%      1673.0        142.5          0.3
max      4767.9        171.8          0.4

In [99]:
x = df2[(df2.State == "punjab") & (df2.Crop_Year == 2010)][["Crop", "Area", "Fertilizer", "Fert_per_ha"]]
print(x.head(8).round(1))

               Crop      Area  Fertilizer  Fert_per_ha
11776     arhar/tur    4200.0    697662.0        166.1
11777         bajra    3000.0    498330.0        166.1
11778        barley   12000.0   1993320.0        166.1
11779  cotton(lint)  483000.0  80231130.0        166.1
11780          gram    2100.0    348831.0        166.1
11781     groundnut    2200.0    365442.0        166.1
11782     guar seed   18200.0   3023202.0        166.1
11783         maize  133000.0  22092630.0        166.1

In [100]:
proxy = {
    "rajasthan": "haryana",
    "chandigarh": "punjab",
    "dadra and nagar haveli": "gujarat",
    "daman and diu": "gujarat",
    "ladakh": "himachal pradesh",
    "andaman and nicobar islands": "kerala",
}

extra = []
for new_state, old_state in proxy.items():
    tmp = ref[ref.State == old_state].copy()
    tmp["State"] = new_state
    extra.append(tmp)

ref_full = pd.concat([ref] + extra, ignore_index=True)
print(ref.shape, "->", ref_full.shape)
print("Missing states:", sorted(set(d.State) - set(ref_full.State)))

(995, 5) -> (1190, 5)
Missing states: []

In [101]:
ref_rain = ref_full[["State", "Crop", "Rain_avg"]]

data = d.merge(ref_rain, on=["State", "Crop"], how="inner")
print(d.shape, "->", data.shape)
print(data.groupby("State").size().sort_values().head(8))

(352947, 7) -> (338115, 8)
State
daman and diu                   41
chandigarh                      65
delhi                          188
dadra and nagar haveli         275
goa                            347
andaman and nicobar islands    622
sikkim                         845
puducherry                     992
dtype: int64

In [102]:
lost = d[~d.set_index(["State","Crop"]).index.isin(ref_rain.set_index(["State","Crop"]).index)]
print("Rows lost:", len(lost))
print(lost["Crop"].value_counts().head(12))

Rows lost: 14832
Crop
other rabi pulses          4648
dry ginger                 2842
other cereals & millets     601
paddy                       474
linseed                     419
papaya                      407
banana                      348
turmeric                    346
mango                       331
tomato                      272
brinjal                     264
oilseeds total              262
Name: count, dtype: int64

In [103]:
x = df2[(df2.State == "punjab") & (df2.Crop_Year == 2010)]["Annual_Rainfall"]
print(x.nunique(), x.unique()[:5])

1 [392.7]

In [104]:
# 1. crop ke naam same karo, generic categories hatao
d["Crop"] = d["Crop"].replace({"paddy": "rice", "dry ginger": "ginger"})
d = d[~d["Crop"].isin(["other rabi pulses", "other cereals & millets", "oilseeds total"])].copy()

# 2. state-wise average rainfall (sab crops milakar)
rain_state = (df2.groupby("State")["Annual_Rainfall"].mean()
                 .rename("Rain_avg").reset_index())

# 3. proxy states ke liye copy
rows = [{"State": new, "Rain_avg": rain_state.loc[rain_state.State == old, "Rain_avg"].iloc[0]}
        for new, old in proxy.items()]
rain_state = pd.concat([rain_state, pd.DataFrame(rows)], ignore_index=True)

# 4. merge
data = d.merge(rain_state, on="State", how="left")
print(d.shape, "->", data.shape)
print("Rainfall missing:", data["Rain_avg"].isna().sum())

(347015, 7) -> (347015, 8)
Rainfall missing: 0

In [105]:
rain_sy = (df2.groupby(["State", "Crop_Year"])["Annual_Rainfall"].mean()
              .rename("Rainfall").reset_index())

# proxy states ke liye copy
rows = []
for new, old in proxy.items():
    t = rain_sy[rain_sy.State == old].copy()
    t["State"] = new
    rows.append(t)
rain_sy = pd.concat([rain_sy] + rows, ignore_index=True)

print(rain_sy.shape)
print(rain_sy.Crop_Year.min(), rain_sy.Crop_Year.max())
print(d.Crop_Year.min(), d.Crop_Year.max())

(794, 3)
1997 2020
1997 2019

In [106]:
data = d.merge(rain_sy, on=["State", "Crop_Year"], how="inner")
print(d.shape, "->", data.shape)
print(data.Crop_Year.value_counts().sort_index())

(347015, 7) -> (341480, 8)
Crop_Year
1997     8729
1998    12122
1999    12905
2000    13459
2001    13202
2002    15062
2003    15494
2004    14002
2005    13760
2006    14359
2007    15134
2008    14845
2009    14999
2010    14864
2011    16038
2012    15849
2013    16501
2014    15723
2015    15585
2016    16638
2017    16905
2018    17220
2019    18085
Name: count, dtype: int64

In [107]:
data = data[["State", "District", "Season", "Crop", "Crop_Year", "Area", "Rainfall", "Yield_q_ha"]].copy()
print(data.isna().sum())
print(data.describe().round(1))

State         0
District      0
Season        0
Crop          0
Crop_Year     0
Area          0
Rainfall      0
Yield_q_ha    0
dtype: int64
       Crop_Year       Area  Rainfall  Yield_q_ha
count   341480.0   341480.0  341480.0    341480.0
mean      2008.7    11611.6    1205.0        43.4
std          6.5    38567.2     640.9       117.9
min       1997.0        0.0     301.3         0.0
25%       2003.0       78.0     815.7         5.1
50%       2009.0      542.0    1075.6        10.0
75%       2014.0     4108.0    1402.7        23.0
max       2019.0  1164800.0    6552.7      1307.0

In [108]:
print((data.Area < 1).sum(), "rows me Area < 1 ha")
print((data.Area < 5).sum(), "rows me Area < 5 ha")
print(data[data.Area < 1][["State","Crop","Area","Yield_q_ha"]].head(5))

60 rows me Area < 1 ha
16683 rows me Area < 5 ha
         State       Crop   Area   Yield_q_ha
275890  kerala  sugarcane  0.300  1104.000000
279345  kerala  sugarcane  0.290  1034.482759
288568  kerala  sugarcane  0.240   833.333333
302343  kerala  sugarcane  0.120   870.833333
302383  kerala  sugarcane  0.121   850.413223

In [109]:
data = data[data.Area >= 5].copy()
print(data.shape)

(324797, 8)

In [110]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error

cat = ["State", "District", "Season", "Crop"]
num = ["Area", "Rainfall"]

X = data[cat + num]
y = np.log1p(data["Yield_q_ha"])

pre = ColumnTransformer([("cat", OneHotEncoder(handle_unknown="ignore"), cat)],
                        remainder="passthrough")
model = Pipeline([("pre", pre),
                  ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                               min_samples_leaf=3, n_jobs=-1, random_state=42))])

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(Xtr, ytr)

pred = np.expm1(model.predict(Xte))
actual = np.expm1(yte)
print("R2 :", round(r2_score(actual, pred), 3))
print("MAE:", round(mean_absolute_error(actual, pred), 2), "q/ha")

R2 : 0.935
MAE: 9.72 q/ha

In [112]:
train = data[data.Crop_Year <= 2016]
test  = data[data.Crop_Year >= 2017]

Xtr2, ytr2 = train[cat + num], np.log1p(train["Yield_q_ha"])
Xte2, yte2 = test[cat + num],  test["Yield_q_ha"]

m2 = Pipeline([("pre", pre),
               ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                            min_samples_leaf=3, n_jobs=-1, random_state=42))])
m2.fit(Xtr2, ytr2)

p2 = np.expm1(m2.predict(Xte2))
print("R2 (future years):", round(r2_score(yte2, p2), 3))
print("MAE:", round(mean_absolute_error(yte2, p2), 2), "q/ha")

R2 (future years): 0.856
MAE: 16.69 q/ha

In [118]:
t = test.assign(pred=p2)
t["abs_err"] = (t.pred - t.Yield_q_ha).abs()
t["pct_err"] = t.abs_err / t.Yield_q_ha * 100
out = t.groupby("Crop").agg(rows=("Crop","size"),
                            MAE=("abs_err","mean"),
                            median_pct_err=("pct_err","median"))
print(out[out.rows > 500].sort_values("median_pct_err").round(1).to_string())

                       rows    MAE  median_pct_err
Crop
banana                  689  101.7            13.5
sweet potato            717   35.5            17.1
sugarcane              1441  151.8            21.5
horse-gram              777    1.6            22.1
garlic                  744   23.4            23.2
wheat                  1470    7.0            23.6
potato                 1618   43.2            25.7
rice                   3287    7.3            26.2
urad                   2382    2.0            26.3
linseed                 750    1.9            26.7
groundnut              1869    5.5            27.4
sesamum                1904    1.5            27.6
maize                  3143    9.5            28.7
ragi                    712    4.6            29.3
onion                  1727   48.0            29.7
barley                  729    7.3            30.1
masoor                 1014    2.9            30.1
other kharif pulses     841    2.5            30.8
moong(green gram)      2483    2.1            31.0
turmeric                810   37.1            33.4
peas & beans (pulses)  1313    7.0            33.7
coriander               775    4.8            34.3
small millets           862    3.4            35.0
dry chillies           1161    9.1            35.2
cotton(lint)            931    9.4            37.2
bajra                  1093    6.3            39.5
castor seed             572    4.4            39.7
arhar/tur              1608    4.1            39.7
rapeseed &mustard      1582    4.7            42.2
cowpea(lobia)           643    3.4            43.2
soyabean                817    5.1            45.0
jowar                  1381    5.9            45.4
gram                   1418    5.2            46.2
sunflower               733    5.3            48.3
ginger                  685   93.8            93.4

In [119]:
t = test.assign(pred=p2)
t["abs_err"] = (t.pred - t.Yield_q_ha).abs()
t["pct_err"] = t.abs_err / t.Yield_q_ha * 100
out = t.groupby("Crop").agg(rows=("Crop","size"),
                            MAE=("abs_err","mean"),
                            median_pct_err=("pct_err","median"))
print(out[out.rows > 500].sort_values("median_pct_err").round(1).to_string())

                       rows    MAE  median_pct_err
Crop
banana                  689  101.7            13.5
sweet potato            717   35.5            17.1
sugarcane              1441  151.8            21.5
horse-gram              777    1.6            22.1
garlic                  744   23.4            23.2
wheat                  1470    7.0            23.6
potato                 1618   43.2            25.7
rice                   3287    7.3            26.2
urad                   2382    2.0            26.3
linseed                 750    1.9            26.7
groundnut              1869    5.5            27.4
sesamum                1904    1.5            27.6
maize                  3143    9.5            28.7
ragi                    712    4.6            29.3
onion                  1727   48.0            29.7
barley                  729    7.3            30.1
masoor                 1014    2.9            30.1
other kharif pulses     841    2.5            30.8
moong(green gram)      2483    2.1            31.0
turmeric                810   37.1            33.4
peas & beans (pulses)  1313    7.0            33.7
coriander               775    4.8            34.3
small millets           862    3.4            35.0
dry chillies           1161    9.1            35.2
cotton(lint)            931    9.4            37.2
bajra                  1093    6.3            39.5
castor seed             572    4.4            39.7
arhar/tur              1608    4.1            39.7
rapeseed &mustard      1582    4.7            42.2
cowpea(lobia)           643    3.4            43.2
soyabean                817    5.1            45.0
jowar                  1381    5.9            45.4
gram                   1418    5.2            46.2
sunflower               733    5.3            48.3
ginger                  685   93.8            93.4

In [120]:
g = data[data.Crop == "ginger"]
print(g.Yield_q_ha.describe().round(1))
print(g.groupby("State")["Yield_q_ha"].median().round(1).sort_values())

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Yield_q_ha, dtype: float64
Series([], Name: Yield_q_ha, dtype: float64)

In [121]:
data = data[data.Crop != "ginger"].copy()
print(data.shape)
print("Ginger bacha:", (data.Crop == "ginger").sum())

(318236, 8)
Ginger bacha: 0

In [122]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error

cat = ["State", "District", "Season", "Crop"]
num = ["Area", "Rainfall"]

X = data[cat + num]
y = np.log1p(data["Yield_q_ha"])

pre = ColumnTransformer([("cat", OneHotEncoder(handle_unknown="ignore"), cat)],
                        remainder="passthrough")
model = Pipeline([("pre", pre),
                  ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                               min_samples_leaf=3, n_jobs=-1, random_state=42))])

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(Xtr, ytr)

pred = np.expm1(model.predict(Xte))
print("R2 :", round(r2_score(np.expm1(yte), pred), 3))
print("MAE:", round(mean_absolute_error(np.expm1(yte), pred), 2), "q/ha")

R2 : 0.939
MAE: 9.23 q/ha

In [123]:
import joblib, os
os.makedirs("models", exist_ok=True)
os.makedirs("data", exist_ok=True)

joblib.dump(model, "models/yield_model.pkl", compress=3)
print("Model size (MB):", round(os.path.getsize("models/yield_model.pkl") / 1e6, 1))

data.to_csv("data/clean_yield_data.csv", index=False)

data.groupby(["State", "District", "Crop"])["Yield_q_ha"].mean().reset_index() \
    .to_csv("data/hist_avg_yield.csv", index=False)

rain_normal = (data.groupby("State")["Rainfall"].mean().round(0)
                   .rename("Rain_normal").reset_index())
rain_normal.to_csv("data/rain_normal.csv", index=False)
print("Saved.")

Model size (MB): 38.0
Saved.

In [124]:
m = joblib.load("models/yield_model.pkl")
sample = pd.DataFrame([{"State": "punjab", "District": "ludhiana", "Season": "kharif",
                        "Crop": "rice", "Area": 50.0, "Rainfall": 600}])
print("Predicted yield (q/ha):", round(float(np.expm1(m.predict(sample)[0])), 1))

Predicted yield (q/ha): 24.9

In [125]:
train = data[data.Crop_Year <= 2016]
test  = data[data.Crop_Year >= 2017]

m3 = Pipeline([("pre", pre),
               ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                            min_samples_leaf=3, n_jobs=-1, random_state=42))])
m3.fit(train[cat + num], np.log1p(train["Yield_q_ha"]))

p3 = np.expm1(m3.predict(test[cat + num]))
print("R2 (future years):", round(r2_score(test["Yield_q_ha"], p3), 3))
print("MAE:", round(mean_absolute_error(test["Yield_q_ha"], p3), 2), "q/ha")

R2 (future years): 0.866
MAE: 15.62 q/ha

In [126]:
x = data[(data.District == "ludhiana") & (data.Crop == "rice")]
print(x[["Crop_Year", "Area", "Rainfall", "Yield_q_ha"]].tail(6).round(1))
print("Asli average yield:", round(x["Yield_q_ha"].mean(), 1))

for r in [390, 600, 1000]:
    s = pd.DataFrame([{"State": "punjab", "District": "ludhiana", "Season": "kharif",
                       "Crop": "rice", "Area": 50.0, "Rainfall": r}])
    print("Rainfall", r, "->", round(float(np.expm1(m.predict(s)[0])), 1))

      Crop_Year      Area  Rainfall  Yield_q_ha
1927       2002  236000.0     301.8        43.2
2136       2000  238000.0     405.3        39.5
2204       2001  235000.0     479.3        39.0
2259       1997  234000.0     690.1        38.4
2429       1999  237000.0     364.4        36.1
2753       1998  241000.0     588.6        32.7
Asli average yield: 41.9
Rainfall 390 -> 25.2
Rainfall 600 -> 24.9
Rainfall 1000 -> 24.9

In [127]:
cat = ["State", "District", "Season", "Crop"]
num = ["Rainfall"]

pre = ColumnTransformer([("cat", OneHotEncoder(handle_unknown="ignore"), cat)],
                        remainder="passthrough")

# asli score: future years
train = data[data.Crop_Year <= 2016]
test  = data[data.Crop_Year >= 2017]
m4 = Pipeline([("pre", pre),
               ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                            min_samples_leaf=3, n_jobs=-1, random_state=42))])
m4.fit(train[cat + num], np.log1p(train["Yield_q_ha"]))
p4 = np.expm1(m4.predict(test[cat + num]))
print("R2 (future years):", round(r2_score(test["Yield_q_ha"], p4), 3))
print("MAE:", round(mean_absolute_error(test["Yield_q_ha"], p4), 2), "q/ha")

R2 (future years): 0.862
MAE: 15.92 q/ha

In [128]:
model = Pipeline([("pre", pre),
                  ("rf", RandomForestRegressor(n_estimators=100, max_depth=25,
                                               min_samples_leaf=3, n_jobs=-1, random_state=42))])
model.fit(data[cat + num], np.log1p(data["Yield_q_ha"]))
joblib.dump(model, "models/yield_model.pkl", compress=3)

for r in [390, 600, 1000]:
    s = pd.DataFrame([{"State": "punjab", "District": "ludhiana", "Season": "kharif",
                       "Crop": "rice", "Rainfall": r}])
    print("Rainfall", r, "->", round(float(np.expm1(model.predict(s)[0])), 1))

Rainfall 390 -> 38.7
Rainfall 600 -> 38.7
Rainfall 1000 -> 38.8

In [129]:
rain_factor = {"Kam": 0.85, "Theek": 1.0, "Zyada": 1.0}
fert_factor = {"Kam": 0.85, "Recommended jitna": 1.0, "Zyada": 1.0}

def final_yield(base_yield, rain_choice, fert_choice):
    return base_yield * rain_factor[rain_choice] * fert_factor[fert_choice]